### PR TITLE
Upgrade to prop-types lib

### PR DESCRIPTION
**Pull request by karlhorky**
Hi, thanks for the library! With versions of React starting with v15.5.0, it will however throw an error due to the use of `React.PropTypes`. This PR depends on the `prop-types` library in order to fix this error.

### CODE REVIEW

**Comment by miracle2k** [comment]
Thanks!

**Comment by karlhorky** [comment]
No worries, thank you for the merge! Do you think you could build and publish a new version on NPM too?

For anyone else looking for a published version in the meantime, I've built and published [`@upleveled/react-arrow`](https://www.npmjs.com/package/@upleveled/react-arrow) (`v1.0.3`).

**Comment by karlhorky** [comment]
@miracle2k any chance of getting a new version published?

**Comment by miracle2k** [comment]
Done now.

**Pull request merged**
